README.md

📝  readeMe 커밋 컨벤션

---

frontend/naemansan/lib/main.dart
frontend/naemansan/lib/screens/home_sccreen.dart
frontend/naemansan/lib/screens/login_screen.dart
frontend/naemansan/lib/screens/screen_index.dart
frontend/naemansan/lib/social_login.dart
frontend/naemansan/lib/tabs/tab_mypage.dart
frontend/naemansan/lib/widgets/login_button.dart

- kakao Login 후 토큰 기기에 저장
- 해당 저장 값 여부로 초기 화면 결정 라우터 셋팅
- 로그아웃 구현
- 로그인 후 뒤로가기 버튼 삭제

✨ Login Token 기기 저장, Logout기능 구현

---

backend/src/main/java/com/dongguk/cse/naemansan/config/SecurityConfig.java
backend/src/main/java/com/dongguk/cse/naemansan/controller/AuthController.java
backend/src/main/java/com/dongguk/cse/naemansan/domain/LoginRequest.java
backend/src/main/java/com/dongguk/cse/naemansan/domain/LoginResponse.java
backend/src/main/java/com/dongguk/cse/naemansan/domain/User.java
backend/src/main/java/com/dongguk/cse/naemansan/domain/type/LoginProviderType.java
backend/src/main/java/com/dongguk/cse/naemansan/domain/type/UserRoleType.java
backend/src/main/java/com/dongguk/cse/naemansan/repository/UserRepository.java
backend/src/main/java/com/dongguk/cse/naemansan/service/AuthService.java
backend/src/main/java/com/dongguk/cse/naemansan/service/KakaoService.java
backend/src/main/resources/application.yml

getAccessToken : 인가 코드를 받고 AccessToken을 social server에 요청해서 받아오는 함수
connectionDB : 해당 AccessToken을 사용해 User의 Data를 받아와 DB에 정보를 확인하고 없으면 DB에 저장하는 함수

✨: login 중 getAccessToken, connectionDB 기능 구현

---

.idea/.gitignore
.idea/2023-1-OSSP2-WeAreBility-3.iml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
backend/src/main/java/com/dongguk/cse/naemansan/config/SpringConfig.java
backend/src/main/java/com/dongguk/cse/naemansan/controller/WalkwayController.java
backend/src/main/java/com/dongguk/cse/naemansan/controller/WalkwayForm.java
backend/src/main/java/com/dongguk/cse/naemansan/domain/Walkway.java
backend/src/main/java/com/dongguk/cse/naemansan/repository/JpaWalkwayRepository.java
backend/src/main/java/com/dongguk/cse/naemansan/repository/Walkwayrepository.java
backend/src/main/java/com/dongguk/cse/naemansan/service/WalkwayService.java

산책로 CRUD, SORT를 위한 Repository, Service, Entity 초기 세팅 완료했습니다.

✨: 산책로 CRUD, sort 초기 세팅

---

frontend/naemansan/ios/Runner/Info.plist
frontend/naemansan/lib/screens/home_sccreen.dart
frontend/naemansan/lib/tabs/tab_home.dart
frontend/naemansan/lib/widgets/banner.dart
frontend/naemansan/lib/widgets/login_button.dart
frontend/naemansan/pubspec.lock
frontend/naemansan/pubspec.yaml

- 현재위치 받아오기
- 아직 샌프라시스코.. 수정필요함

✨NowLocation

---

.gitattributes
.gitignore
.idea/.gitignore
.idea/2023-1-OSSP2-WeAreBility-3.iml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
.vscode/settings.json
frontend/naemansan/build/windows/flutter/Debug/flutter_wrapper_app.pdb
frontend/naemansan/build/windows/flutter/Debug/flutter_wrapper_plugin.pdb

잘못된 commit, push, PR로 인한 충돌 오류 제거했습니다.

🚑: 충돌 오류 제거

---

backend/sql/naemansan_ddl.sql
backend/src/main/java/com/dongguk/cse/naemansan/controller/UserController.java
backend/src/main/java/com/dongguk/cse/naemansan/domain/Image.java
backend/src/main/java/com/dongguk/cse/naemansan/domain/User.java
backend/src/main/java/com/dongguk/cse/naemansan/dto/TokenDto.java
backend/src/main/java/com/dongguk/cse/naemansan/dto/UserRequestDto.java
backend/src/main/java/com/dongguk/cse/naemansan/service/UserService.java

User
C : 로그인 시
R : get
U : put
D : delete
이미지 경로를 제외한 기능 구현했습니다.

✨ feat: User Profile delete 기능 추가

---

backend/src/main/java/com/dongguk/cse/naemansan/domain/Course.java
backend/src/main/java/com/dongguk/cse/naemansan/domain/type/CourseTagType.java
backend/src/main/java/com/dongguk/cse/naemansan/repository/CourseTypeRepository.java
backend/src/main/java/com/dongguk/cse/naemansan/repository/JpaCourseRepository.java
backend/src/main/java/com/dongguk/cse/naemansan/repository/JpaCourseTypeRepository.java
backend/src/main/java/com/dongguk/cse/naemansan/service/CourseService.java

산책로 CREATE 중 DB에 insert가 되지 않는 오류 수정 중입니다

🐛  산책로 CREATE 기능 bug 수정중

---

frontend/naemansan/ios/Runner/Info.plist
frontend/naemansan/lib/services/login_api_service.dart
frontend/naemansan/lib/tabs/tab_home.dart
frontend/naemansan/lib/tabs/tab_mypage.dart
frontend/naemansan/lib/widgets/login_button.dart
frontend/naemansan/pubspec.yaml

- google geocoding API 의존성 추가
- 한글화 적용

✨ 위치 한글화 적용

---

backend/src/main/java/com/dongguk/cse/naemansan/controller/AuthenticationController.java
backend/src/main/java/com/dongguk/cse/naemansan/controller/CourseController.java
backend/src/main/java/com/dongguk/cse/naemansan/controller/FollowController.java
backend/src/main/java/com/dongguk/cse/naemansan/controller/NotificationController.java
backend/src/main/java/com/dongguk/cse/naemansan/repository/CourseRepository.java
backend/src/main/java/com/dongguk/cse/naemansan/service/CourseService.java
backend/src/main/java/com/dongguk/cse/naemansan/service/FollowService.java
backend/src/main/java/com/dongguk/cse/naemansan/service/GoogleService.java
backend/src/main/java/com/dongguk/cse/naemansan/service/KakaoService.java
backend/src/main/java/com/dongguk/cse/naemansan/service/NotificationService.java

- Login 간소화 인가코드를 보내지 않고 로그인 시 바로 jwt를 발급하는 방식
- 코드 규격화를 위한 기초 세팅

🎨 ✨  Login 간소화 작업 및 팔로우, 알림 기능 기초 세팅

---

backend/src/main/java/com/dongguk/cse/naemansan/controller/NotificationController.java
backend/src/main/java/com/dongguk/cse/naemansan/domain/Notification.java
backend/src/main/java/com/dongguk/cse/naemansan/dto/NotificationDto.java
backend/src/main/java/com/dongguk/cse/naemansan/repository/NotificationRepository.java
backend/src/main/java/com/dongguk/cse/naemansan/service/NotificationService.java

- 알림은 서버에서 자동으로 만들어서 DB에 저장하므로 Create 삭제
- Read, Update, Delete 버그 fix

🐛 알림 CRUD 버그 수정

---

backend/src/main/java/com/dongguk/cse/naemansan/controller/AuthenticationController.java
backend/src/main/java/com/dongguk/cse/naemansan/controller/CourseController.java
backend/src/main/java/com/dongguk/cse/naemansan/controller/ImageController.java
backend/src/main/java/com/dongguk/cse/naemansan/controller/UserController.java
backend/src/main/java/com/dongguk/cse/naemansan/dto/CommentDto.java
backend/src/main/java/com/dongguk/cse/naemansan/dto/response/CourseDto.java
backend/src/main/java/com/dongguk/cse/naemansan/repository/LikeRepository.java
backend/src/main/java/com/dongguk/cse/naemansan/service/CommentService.java
backend/src/main/java/com/dongguk/cse/naemansan/service/CourseService.java
backend/src/main/java/com/dongguk/cse/naemansan/service/ImageService.java
backend/src/main/java/com/dongguk/cse/naemansan/service/UserService.java

🐛 Request, Response 오류 수정

---

backend/src/main/java/com/dongguk/cse/naemansan/controller/CourseController.java
backend/src/main/java/com/dongguk/cse/naemansan/controller/UserController.java
backend/src/main/java/com/dongguk/cse/naemansan/domain/Course.java
backend/src/main/java/com/dongguk/cse/naemansan/domain/User.java
backend/src/main/java/com/dongguk/cse/naemansan/domain/UsingCourse.java
backend/src/main/java/com/dongguk/cse/naemansan/repository/UsingCourseRepository.java
backend/src/main/java/com/dongguk/cse/naemansan/service/UserService.java

✨ 개인 User 조회 기능 구현

---

backend/.gitignore
backend/src/main/java/com/dongguk/cse/naemansan/service/AuthenticationService.java
backend/src/main/java/com/dongguk/cse/naemansan/service/ImageService.java
backend/src/main/resources/application.yml

image download error 제거
yml 파일 local, server 분리

🚑 ignore 변경, image download error in server

---

backend/.gitignore
backend/src/main/java/com/dongguk/cse/naemansan/controller/NotificationController.java

json 파일 형식 gitignore 파일에 추가해 무시하도록 했습니다

🐛 🚑  json 파일 형식 gitignore 추가

---

frontend/naemansan/lib/main.dart
frontend/naemansan/lib/screens/Login/webview_google_screen.dart
frontend/naemansan/lib/screens/Login/webview_kakao_screen.dart
frontend/naemansan/lib/screens/create_course_screen.dart
frontend/naemansan/lib/screens/webview_kakao_screen.dart
frontend/naemansan/lib/services/login_api_service.dart
frontend/naemansan/lib/tabs/tab_home.dart
frontend/naemansan/lib/tabs/tab_mypage.dart
frontend/naemansan/lib/widgets/login_button.dart
frontend/naemansan/pubspec.yaml

♻️ Refactoring front

---

frontend/naemansan/lib/screens/Login/webview_kakao_screen.dart
frontend/naemansan/lib/screens/login_screen.dart
frontend/naemansan/lib/tabs/tab_home.dart
frontend/naemansan/lib/tabs/tab_mypage.dart
frontend/naemansan/lib/widgets/banner.dart

``` dart
WidgetsBinding.instance.addPostFrameCallback((_) {
_asyncMethod();
});
```
init 상태에서 로그인 체크 비동기로 가능하게 만들어서 해결

🐛  새로고침시 로그인 풀리는 현상

---

backend/src/main/java/com/dongguk/cse/naemansan/common/ErrorCode.java
backend/src/main/java/com/dongguk/cse/naemansan/controller/AdminController.java
backend/src/main/java/com/dongguk/cse/naemansan/controller/CommonController.java
backend/src/main/java/com/dongguk/cse/naemansan/controller/UserController.java
backend/src/main/java/com/dongguk/cse/naemansan/domain/Notice.java
backend/src/main/java/com/dongguk/cse/naemansan/dto/CourseTagDto.java
backend/src/main/java/com/dongguk/cse/naemansan/dto/request/EnrollmentCourseRequestDto.java
backend/src/main/java/com/dongguk/cse/naemansan/dto/request/NoticeRequestDto.java
backend/src/main/java/com/dongguk/cse/naemansan/dto/response/EnrollmentCourseDetailDto.java
backend/src/main/java/com/dongguk/cse/naemansan/dto/response/EnrollmentCourseListDto.java
backend/src/main/java/com/dongguk/cse/naemansan/dto/response/NoticeDetailDto.java
backend/src/main/java/com/dongguk/cse/naemansan/dto/response/NoticeListDto.java
backend/src/main/java/com/dongguk/cse/naemansan/repository/NoticeRepository.java
backend/src/main/java/com/dongguk/cse/naemansan/service/CommonService.java
backend/src/main/java/com/dongguk/cse/naemansan/service/CourseService.java
backend/src/main/java/com/dongguk/cse/naemansan/service/UserService.java
backend/src/main/java/com/dongguk/cse/naemansan/util/CourseUtil.java

- Create: /admin/notice
- Update: /admin/notice/{id}
- Delete: /admin/notice/{id}
- Read: /notice/list or /notice/{id}

✨공지사항 기능 추가

---

backend/sql/naemansan_ddl.sql
backend/src/main/java/com/dongguk/cse/naemansan/repository/CommentRepository.java
backend/src/main/java/com/dongguk/cse/naemansan/repository/EnrollmentCourseRepository.java
backend/src/main/java/com/dongguk/cse/naemansan/repository/UserRepository.java
backend/src/main/java/com/dongguk/cse/naemansan/security/jwt/JwtProvider.java
backend/src/main/java/com/dongguk/cse/naemansan/util/Oauth2Util.java

- Refresh Token에 UserID Data 안 들어가던 오류 해결
- DDL Update

🐛🎨  Refresh Token Error, DDL update

---

frontend/naemansan/android/app/src/main/AndroidManifest.xml

🚑 fix : Android Naver Map API

---

frontend/naemansan/lib/main.dart
frontend/naemansan/lib/models/mytap_trail_model.dart
frontend/naemansan/lib/providers/keyword.dart
frontend/naemansan/lib/screens/map/create_title_map.dart
frontend/naemansan/lib/screens/map/naver_map_screen.dart
frontend/naemansan/lib/services/courses_api.dart
frontend/naemansan/lib/tabs/tab_home.dart
frontend/naemansan/lib/tabs/tab_myrail.dart
frontend/naemansan/lib/widgets/horizontal_slider.dart
frontend/naemansan/lib/widgets/main_card.dart
frontend/naemansan/lib/widgets/main_slider.dart
frontend/naemansan/lib/widgets/widget_mytrail.dart
frontend/naemansan/lib/widgets/widget_trail.dart

- map post성공
- 개인산책로 모델 생성 
- 개인 산책로 GET 적용

✨ MAP POST

---

backend/src/main/java/com/dongguk/cse/naemansan/controller/NotificationController.java
backend/src/main/java/com/dongguk/cse/naemansan/util/NotificationUtil.java

⚡  푸시알림 테스트 완료
